### ISSUE TITLE
Any reason why Set doesn't have a map method?

### ISSUE THREAD

**Issue by enumag** [php-ds/extension#110]
```
public Ds\Set Ds\Set::map ( callable $callback )
```

It's not even listed in #90. Is there some reason why this method can't or shouldn't be added?

**Comment by rtheunissen** [comment]
What would you expect it to return?

**Comment by teohhanhui** [comment]
`map` returns a `Map`. Makes perfect sense, no? :laughing:

**Comment by TheDigitalOrchard** [comment]
+1 for adding a map() method. It makes perfect sense to mirror `array_map` functionality in these DS classes, where appropriate.

It should return a Set (not a Map) since it's merely a filtered/processes set/subset of itself, much like `array_map()` accepts an array and returns an array.

> array_map() returns an array containing all the elements of array1 after applying the callback function to each one. The number of parameters that the callback function accepts should match the number of arrays passed to the array_map()

But unlike @rtheunissen's example code, it should _return_ a new set instead of modifying the existing one, I think, as shown here:

```
$s1 = new \Ds\Set();
$s1[] = 1;
$s1[] = 2;
$s1[] = 3;

$s2 = $s1->map(function($value) {
    return $value % 2;
});

print_r($s2);
```

**Comment by rtheunissen** [comment]
> But unlike @rtheunissen's example code, it should return a new Set instead of modifying by reference

Yeah this was my bad - `map` should **definitely** return a mapped copy. It would be very unusual for methods like `map` and `filter` to mutate the instance. If you wanted a `map` that mutates, I'd rather implement something like `apply` that does that.

**Comment by teohhanhui** [comment]
No, it should definitely not modify the original.

**Comment by rtheunissen** [comment]
> No, it should definitely not modify the original.

That's what I'm saying, yes. 👍

**Comment by simPod** [comment]
Any reason for closing this? I just found myself `array_map`ping `Set->toArray()` several times this week already. I think the FR is still viable, no?
