### ISSUE TITLE
Questions and what now...

### ISSUE THREAD

**Issue by TheCelavi** [php-ds/extension#4]
Hello,

This is AWESOME! I have few questions:

1. Why did you use "\Ds" namespace, why not "\DataStructure"? It is more explanatory, I know it is related to coding style, but I can not see reason why did you use abbreviation... 
2. It seams that Binary Tree, Balanced Binary Tree and maybe B+ Tree is missing... Did you planned to add these data structures as well?
3. This is most important - there is no alternative pure PHP implementation. I believe that popularity of this PHP extension depends on alternative pure PHP implementation. To explain this, here is the example: via Composer, I would include in my project pure PHP implementation of your data structures. In one point of time, in order to speed my application, I will remove pure PHP implementation and install dedicated PHP extension.

What is scary about PHP extensions that you can have a project which requires upgrade of PHP and some of the extensions are not easy to recompile for upgraded version.

Here is the example: https://github.com/AOP-PHP/AOP this was AWESOME extension, pure awesomeness... However, every library that depends on this extension is scr***ed, unusable.

There are awesome extensions out there for PHP, like this one - but do have in mind that we are scared that things can go wrong as for AOP extension. Pure PHP implementation would ensure us that there is fail safe strategy.

Thanks for your time. Hope you find these suggestions and questions useful.

**Comment by jkuchar** [comment]
1. :+1: 
3. This can be awesome. However pure PHP implementation will probably be super slow in comparison to this one. (however that will be feature, right?)

**Comment by TheCelavi** [comment]
One more argument for proposal nb. 3. 

See Twig: http://twig.sensiolabs.org/doc/installation.html there is a C extension that bust performance. It is optional. 

I belive that for this library same concept is a wining mix. If you agree, open github repo and we will contribute.

**Comment by dantudor** [comment]
This would be a great advantage to have both options available

**Comment by rtheunissen** [comment]
> Why did you use "\Ds" namespace, why not "\DataStructure"? It is more explanatory, I know it is related to coding style, but I can not see reason why did you use abbreviation

I felt that it's closer to the name of the project, *php-ds*. `\Ds` is short and easy to remember, exactly how `PDO` and `SPL` are as well. `\Ds\Vector` is a lot nicer than `\DataStructures\Vector`. The namespace is not final at this stage and API is not stable. I'd be happy to consider any alternatives.

> It seams that Binary Tree, Balanced Binary Tree and maybe B+ Tree is missing... Did you planned to add these data structures as well?

I don't currently have any plans for trees, at least not before immutable structures and graphs. I don't believe there's a use case where you **need** an RB or B+ tree (where a Set or Map wouldn't do a decent job). I don't want to include a structure simply because the textbooks say so. I would be happy to include anything if you can preset a good use case that can't be nicely implemented using the existing structures. 

Java doesn't have a balanced tree implementation either, but does use it internally for `TreeSet` amongst others. `ds::set` provides an `O(n log n)` sort for when you want to work with sorted data, much like an `array`. That's good enough for 1.0

> there is no alternative pure PHP implementation. I believe that popularity of this PHP extension depends on alternative pure PHP implementation

I like this, in fact there *was* a pure PHP implementation for a while but it was too much work to update both when something changed. I am open to the idea of a PHP implementation that offers the same behaviour. What's nice about extensions + composer is that extensions take priority, so all you need to do is install the extension to improve the performance of your application. 

I'm not 100% sold on this, but it's definitely on my mind. It's one of the things to consider when the API is stable, ie. 1.0

---

Thanks for the suggestions, :+1:

**Comment by rtheunissen** [comment]
> If you agree, open github repo and we will contribute.

Why not this repo under `/php`?

**Comment by rtheunissen** [comment]
@TheCelavi @jkuchar @dantudor see #8

**Comment by dantudor** [comment]
@rtheunissen How do you intend to proceed with the polyfill? I'm happy to contribute to the development. 

Is the intention that we backport the polyfill to PHP<7, or should it just act as an intermediate for PHP7 but without the extension installed? 

Once there is the core code taken from the statics we can create issues for the development. 

I have time to migrate the statics and composered test dependencies if you require.

Dan

**Comment by rtheunissen** [comment]
@dantudor I don't see a reason why we can't support 5.6 as well. So the polyfill should focus entirely on behaviour and compatibility.  A good start will be to migrate the stubs and implement them. 

I'll do that migration and report back when we're set to start filling in the gaps.

**Comment by rtheunissen** [comment]
@dantudor I've copied the stubs over to https://github.com/php-ds/polyfill. We can start implementing the structures there.

**Comment by designermonkey** [comment]
@rtheunissen is there any progress on immutability? I have seen there is a reference to it in the `common.h` file, but as I'm not a C developer, I can't figure out if it is ever used, and if I can create immutable structures using DS.

**Comment by rtheunissen** [comment]
@designermonkey This project does not currently provide support for immutable data structures. I have been working on persistent data structures over the last couple of years and will introduce them to this project soon, along with some other nice things like typed allocations.

**Comment by designermonkey** [comment]
Great @rtheunissen, thanks! It would be great to have some kind of struct maybe?

**Comment by rtheunissen** [comment]
@designermonkey what is your ideal for what that might look like? Keep in mind that we are limited by the syntax already supported by the language, so a first class `struct` type would need to be a language-level feature, or implemented as an entirely separate extension.

**Comment by designermonkey** [comment]
I'm not entirely sure, but I had a go and implemented this: https://github.com/jorpo-co/struct

My reasoning is that it's not written in C, so wouldn't be able to make use of low level optimisations etc. I would prefer things like this to be proper PHP types. We can only hope :)
