### ISSUE TITLE
Consider replacing Vector and Deque with Sequence as a class (not an interface)

### ISSUE THREAD

**Issue by rtheunissen** [php-ds/extension#45]
The differences between `Deque` and `Vector` might be considered small enough to consider removing `Vector` and `Sequence`, and rename `Deque` to Sequence. 

Advantages of `Deque`:
- O(1) unshift and shift

Advantages of `Vector`:
- 1.5x growth factor yields less average memory used than Deque's 2.0x
- Slightly faster access time due to not having to translate into the buffer.

`Sequence` is also the only interface below `Collection`.

The important question is: **is it clear enough when you would use one over the other?**

**Comment by castarco** [comment]
I think that these two classes should remain separated. Maybe the documentation should include two well defined usage cases in order to make easier to programmers choose which class to pick .

**Comment by rtheunissen** [comment]
@castarco why do you think they should remain separated?

**Comment by castarco** [comment]
Hi @rtheunissen , mainly because it's very interesting to keep the advantages of both data structures.

If the programmer knows in advance that the container won't be resized, or that the resize will be done only due to append operations (and NOT prepend ops)... then it should be crystal clear that Vector is the correct choice (over Deque or even over the native PHP "array").

There is no need to justify the Deque existence because it's more flexible than Vector, but maybe the programmers should know at which price. It's a good thing to allow the programmers to exploit this "forgotten" knowledge and optimize their programs.

**Comment by rtheunissen** [comment]
@castarco I completely agree that it's ideal to keep the advantages of both structures, but I believe that the overhead of having two structures that are *practically* identical outweighs those benefits. The minor differences between them are that a Vector is very slightly faster to access and modify at the end of the sequence (but has the same complexity as Deque), and the growth factor is 1.5 vs Deque's 2.0. Deque has **significant** advantage of offering O(1) ops at the front of the sequence. That to me is enough to make Deque the default, thereby making Vector practically redundant. 

Keep in mind that this is with the introduction of Tuple (think SplFixedArray but better), which would consume some of the use cases where you might have used Vector. This would be where growth is not expected, or in read-only contexts. 

See https://github.com/php-ds/extension/issues/52

**Comment by castarco** [comment]
Hum, it's true that a Tuple type will cover more than the 50% of the `Vector` class use cases.

**Comment by rtheunissen** [comment]
Sequence should still be an interface, and will remain so in 2.0
