### ISSUE TITLE
Consider adding a `setSlice` method to Vector or "similar" classes

### ISSUE THREAD

**Issue by castarco** [php-ds/extension#66]
Hello,

I've been working with Ds\Vector and I'm missing a method to move data between collections efficiently.

Something like...

```php
/**
  * @param array|Sequence $source
  * @param int $targetStart
  * @param int $sourceStart
  * @param null|int $length
  */
public function setSlice($source, int $targetStart=0, int $sourceStart=0, int $length=null);

/**
  * Another potentially interesting method.
  * This is similar to `push`, but it allows passing slices instead of complete containers.
  *
  * @param array|Sequence $source
  * @param int $sourceStart
  * @param null|int $length
  */
public function appendSlice($source, int $sourceStart=0, int $length=null);
```

This is interesting because we don't have any method to create slices as "views", slices can only be created as completely new containers, even if the slice is a shallow copy, when storing scalars, this is equivalent to deep copies.

**Comment by castarco** [comment]
P.D.: Before doing anything, I prefer to know if this seems a good idea to project maintainers, and if this methods should be implemented on the `Vector` "successors" instead of on `Vector`.

**Comment by rtheunissen** [comment]
I really like the idea of views, or rather lazy collections, such that something like `$map->keys()->sum()` wouldn't need to create a sequence of keys in order to sum them. 

As for `setSlice` and `appendSlice`, they seem to achieve the same thing as `splice`, maybe `insert` too? If you find that you use these a lot, create a new collection under your own namespace and implement them. Both would be a basic loop with fast array access.
