### ISSUE TITLE
memtest failed

### ISSUE THREAD

**Issue by vringar** [php-ds/extension#75]
I'm sorry to open an issue for this but I am just incredibly lost.

I am running PHP 7.0.15-0 on an Ubuntu 16.10 and my memtest just returned 594 errors. 
Is this a problem and if so what do i need to do?

[I attached the log ](https://github.com/php-ds/extension/files/817275/memtest_result.txt).

**Comment by rtheunissen** [comment]
These seem similar to the [suppressions we're using](https://github.com/php-ds/extension/blob/master/.travis.supp) for memtest to "pass" on Travis CI. They're not caused by anything in the extension, but by PHP itself. @nikic or @krakjoe might have better insight here. 

I noticed that you're not running a dev build of PHP. I believe that's why you're seeing those ???'s in the log. It's not a big deal but could make fixing these more difficult than it needs to be.

**Comment by nikic** [comment]
@rtheunissen As these are not leaks but uses of uninit values it should not be related to the suppressions. The PHP build does seem to have debug symbols, but they are missing for some parts. Maybe specifying ZEND_DONT_UNLOAD_MODULES=1 will help.
